### ISSUE TITLE
Question on pause time

### ISSUE THREAD

**Issue by tmigone** [nokenwa/twilio-media-stream-live-transcription-node#5]
Hey, is it possible to keep the media stream open for indefinite or at least big chunks of time? I could not find a maximum time for the pause verb. I want to stream audio from a 1/2 hours call for instance.

**Comment by nokenwa** [comment]
Hiya, Twilio limits your call to 4 hours. So you can stream for 4 hours non stop theoretically. 

In this example, the limit would come from the Google Transcription service which has a limit of about a minute.
https://cloud.google.com/speech-to-text/quotas#content
